In [1]:
for i in range (5):
    print(i)

0
1
2
3
4


In [7]:
list2 = [1,2,3,4]
type(list2)

list

In [4]:
list1 = (1,10,5,4)
type(list1)

tuple

In [10]:
list2.sort()

In [17]:
list1 = ['a','b']
for var1 in list1:
    print('Var1 is= ',var1)
    for var2 in range(4):
        print('*')
        for var3 in range (1):
            print('%')
    

Var1 is=  a
*
%
*
%
*
%
*
%
Var1 is=  b
*
%
*
%
*
%
*
%


In [2]:
n = 5
for i in range (1,n):
    print('val')
    for j in range (1,n):
        print('*',end = '  ')
    print()
    

val
*  *  *  *  
val
*  *  *  *  
val
*  *  *  *  
val
*  *  *  *  


In [69]:
chr(1)

'\x01'

In [86]:
n = 11

for i in range (1,n):
    chr = 1
    print(f'Enter ', '  ')
    for j in range (i):
        print(chr,end = '  ')
        chr = chr + 1
    print()

Enter    
1  
Enter    
1  2  
Enter    
1  2  3  
Enter    
1  2  3  4  
Enter    
1  2  3  4  5  
Enter    
1  2  3  4  5  6  
Enter    
1  2  3  4  5  6  7  
Enter    
1  2  3  4  5  6  7  8  
Enter    
1  2  3  4  5  6  7  8  9  
Enter    
1  2  3  4  5  6  7  8  9  10  


In [77]:
chr(97)

'a'

In [2]:
s1 = {'Mumbai','Pune','Delhi','Hyderabad'}
s1.remove('Pune')

In [3]:
s1

{'Delhi', 'Hyderabad', 'Mumbai'}

In [4]:
s1.discard('Hyderabad')

In [5]:
s1

{'Delhi', 'Hyderabad', 'Mumbai'}

In [6]:
s1.discard('Hyderabad')

In [7]:
s1

{'Delhi', 'Mumbai'}

In [9]:
s1.pop()

'Delhi'

In [10]:
s1

{'Mumbai'}

In [11]:
s1.pop()

'Mumbai'

In [12]:
s1

set()

In [13]:
type(s1)

set

In [16]:
s1 = {'Mumbai','Pune','Delhi','Hyderabad'}
s1.add('chennai')
s1

{'Delhi', 'Hyderabad', 'Mumbai', 'Pune', 'chennai'}

In [18]:
s2 = {'katraj','vadgaon','shivaji nagar'}
s1.update(s2)
s1

{'Delhi',
 'Hyderabad',
 'Mumbai',
 'Pune',
 'chennai',
 'katraj',
 'shivaji nagar',
 'vadgaon'}

In [19]:
s1.pop()
s1

{'Hyderabad',
 'Mumbai',
 'Pune',
 'chennai',
 'katraj',
 'shivaji nagar',
 'vadgaon'}

In [20]:
s1.pop()
s1

{'Hyderabad', 'Mumbai', 'Pune', 'chennai', 'katraj', 'shivaji nagar'}

In [21]:
del s1[1]

TypeError: 'set' object doesn't support item deletion

In [22]:
s1.remove('Mumbai')

In [23]:
s1


{'Hyderabad', 'Pune', 'chennai', 'katraj', 'shivaji nagar'}

In [24]:
dict1 = {}
type(dict1)

dict

In [25]:
s1

{'Hyderabad', 'Pune', 'chennai', 'katraj', 'shivaji nagar'}

In [26]:
del s1[2]

TypeError: 'set' object doesn't support item deletion

In [27]:
s1

{'Hyderabad', 'Pune', 'chennai', 'katraj', 'shivaji nagar'}

In [28]:
s2 = {1,2,3,4,5,6}
s1.update(s2)

In [29]:
s1

{1, 2, 3, 4, 5, 6, 'Hyderabad', 'Pune', 'chennai', 'katraj', 'shivaji nagar'}

In [32]:
s1 = {'Hyderabad', 'Pune', 'chennai', 'katraj', 'shivaji nagar'}
s2 = {1,2,3,4,5,6}
s1.update(s2)
s2.update(s1)
print('Set1 is ',s1)
print('Set2 is ',s2)

Set1 is  {1, 2, 3, 4, 5, 'Pune', 6, 'chennai', 'shivaji nagar', 'Hyderabad', 'katraj'}
Set2 is  {1, 2, 3, 4, 5, 6, 'Pune', 'chennai', 'shivaji nagar', 'Hyderabad', 'katraj'}


Union()

In [37]:
s1 = {1,2,3,4,5,6}
s2 = {'a','b','c','d','e','f'}
s3 = s1.union(s2)
print('s1 =',s1)
print('s2 =',s2)
print('s3 =',s3)

s1 = {1, 2, 3, 4, 5, 6}
s2 = {'c', 'f', 'a', 'e', 'b', 'd'}
s3 = {1, 2, 3, 4, 5, 6, 'c', 'f', 'a', 'e', 'b', 'd'}


In [39]:
s1 = {1,2,3,4,5,6}
s2 = {'a','b','c','d','e','f',6}
s3 = s1.intersection(s2)
print('s1 =',s1)
print('s2 =',s2)
print('s3 =',s3)

s1 = {1, 2, 3, 4, 5, 6}
s2 = {6, 'c', 'f', 'a', 'e', 'b', 'd'}
s3 = {6}


In [40]:
s1 = {1,2,3,4,5,6}
s2 = {'a','b','c','d','e','f',6}
s3 = s1.difference(s2)
print('s1 =',s1)
print('s2 =',s2)
print('s3 =',s3)

s1 = {1, 2, 3, 4, 5, 6}
s2 = {6, 'c', 'f', 'a', 'e', 'b', 'd'}
s3 = {1, 2, 3, 4, 5}


In [42]:
s1 = {1,2,3,4,5,6}
s2 = {'a','b','c','d','e','f',6}
s3 = s1.difference_update(s2)
print('s1 =',s1)
print('s2 =',s2)
print('s3 =',s3)

s1 = {1, 2, 3, 4, 5}
s2 = {6, 'c', 'f', 'a', 'e', 'b', 'd'}
s3 = None


In [43]:
s1 = {'Mumbai','Pune','Delhi','Hyderabad'}
s2 = {'katraj','vadgaon','shivaji nagar','Pune'}
s3 = s1.intersection(s2)
print ('s3',s3)

s3 {'Pune'}


In [47]:
s1 = {'Mumbai','Pune','Delhi','Hyderabad'}
s2 = {'katraj','vadgaon','shivaji nagar','Pune'}
s3 = s1.intersection_update(s2)
print ('s3',s3)


s3 None


In [50]:
a = {1,2,3,4,5,6}
b = {7,8,9,10,11,12}
b1 = a.c
print ('b', b)

b {1, 2, 3, 4, 5, 6}


In [54]:
a = {1,2,3,4,5,6}
b = {7,8,9,10,11,12}
type(b)

set

In [57]:
max(b)

12

In [58]:
sum (a)

21

In [1]:
d1 = {'Player_Name2':'Sachin', 'Age':'42','last_five score':'200,100,90,80,78','Player_Name2':'Sachin'}
d1

{'Player_Name2': 'Sachin', 'Age': '42', 'last_five score': '200,100,90,80,78'}

In [5]:
d1.get('Player name2')

In [6]:
d1.keys()

dict_keys(['Player_Name2', 'Age', 'last_five score'])

In [7]:
d1.values()

dict_values(['Sachin', '42', '200,100,90,80,78'])

In [8]:
d1.items()

dict_items([('Player_Name2', 'Sachin'), ('Age', '42'), ('last_five score', '200,100,90,80,78')])

In [10]:
for keys in d1.keys():
    print('Keys are ', keys)

Keys are  Player_Name2
Keys are  Age
Keys are  last_five score


In [12]:
for values in d1.values():
    print('Values are ', values)

Values are  Sachin
Values are  42
Values are  200,100,90,80,78


In [13]:
d1

{'Player_Name2': 'Sachin', 'Age': '42', 'last_five score': '200,100,90,80,78'}

In [17]:
d1['Age'] = '41'

In [15]:
d1

{'Player_Name2': 'Sachin', 'Age': 41, 'last_five score': '200,100,90,80,78'}

In [23]:
d1 ['High score'] = '200'
d1

{'Player_Name2': 'Sachin',
 'Age': '41',
 'last_five score': '200,100,90,80,78',
 'High score': '200'}

In [25]:
d2 = {'ID':'4444', 'Place':'Mumbai'}
d1.update(d2)
d1

{'Player_Name2': 'Sachin',
 'Age': '41',
 'last_five score': '200,100,90,80,78',
 'High score': '200',
 'ID': '4444',
 'Place': 'Mumbai'}

{'Player_Name2': 'Sachin',
 'last_five score': '200,100,90,80,78',
 'High score': '200',
 'Place': 'Mumbai'}

In [39]:
d1

{'Player_Name2': 'Sachin',
 'last_five score': '200,100,90,80,78',
 'High score': '200',
 'Place': 'Mumbai'}

In [40]:
del d1['Place']

In [41]:
d1

{'Player_Name2': 'Sachin',
 'last_five score': '200,100,90,80,78',
 'High score': '200'}

In [44]:
d1.popitem()

('High score', '200')

In [77]:
for i in range(1,10):
    square_dict = i ** 3
    print ('square_dict  ',square_dict)

square_dict   1
square_dict   8
square_dict   27
square_dict   64
square_dict   125
square_dict   216
square_dict   343
square_dict   512
square_dict   729


In [4]:
def my_function():
    print('hello python')
    print('we are learning python and data science')
    for i in range (15,20):
        print('Value of i = ',i)
        
my_function()
my_function()

hello python
we are learning python and data science
Value of i =  15
Value of i =  16
Value of i =  17
Value of i =  18
Value of i =  19
hello python
we are learning python and data science
Value of i =  15
Value of i =  16
Value of i =  17
Value of i =  18
Value of i =  19


In [5]:
 for i in range (15,20):
        print('Value of i = ',i)

Value of i =  15
Value of i =  16
Value of i =  17
Value of i =  18
Value of i =  19


In [6]:
def addition(list1)
    print('Input list is ',list1)
    add = 0
    for num in list1:
        add = add + num
        print('Addition of list',list1)

SyntaxError: invalid syntax (<ipython-input-6-561afd9e4806>, line 1)

In [13]:
list1 = [1,2,3,4]
list2 = [1,2,3,4]
x = map(lambda x,y:x + y, list1,list2)
tuple(x)

(2, 4, 6, 8)

In [16]:
str1 = 'vikas'
str2 = 'shraddha'
x = map(lambda x,y:x + y, str1,str2)
list(x)

['vs', 'ih', 'kr', 'aa', 'sd']

In [8]:
list(filter(lambda x: x %2 != 0, range(1,10) ))

[1, 3, 5, 7, 9]

In [45]:
list1 = [1,3,5,7,9]
list2 = [2,3,4,5,6]

val = list(map(lambda a,b: a+b,list1,list2))
print(val)

[3, 6, 9, 12, 15]


In [32]:

list(map(lambda x:x**2,range(1,11)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [46]:
list(map(lambda a:a**3,range(1,11) ))


[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [47]:
list(filter(lambda a:a % 2 == 0,range(1,11)))

[2, 4, 6, 8, 10]

In [24]:
#list= [2, 4, 6, 8, 10]
sum(list)

14

In [5]:
sum = 0
for i in range (1,11):
    print('i',i)
    sum = sum + i

print('sum',sum)


i 1
i 2
i 3
i 4
i 5
i 6
i 7
i 8
i 9
i 10
sum 55


In [9]:
a = 5
x = list(map(lambda a: a*i, i in range(1,11)))
print('x')

TypeError: 'bool' object is not iterable

In [1]:
numbers1 = [1, 2, 3]
type(numbers1)
numbers1 = [1, 2, 3]
  
result = tuple((map(lambda x, y: x + y, numbers1, numbers2)))
print(result)

(5, 7, 9)


# Double all numbers using map and lambda

In [10]:
numbers = [1, 2, 3, 4]
list(map(lambda x: x + x, numbers))


[2, 4, 6, 8]

# zip

In [12]:
list1 = ['vikas', 'vikram', 'Dinesh']
list2 = [2,3,4]
dict(zip(list1,list2))


{'vikas': 2, 'vikram': 3, 'Dinesh': 4}

In [15]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
new_list =[]
for i in l1:
    print(i)
    for n in i:
        new_list.append(n)
print(new_list)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [24]:
l1 = [11,22,33]
b =[]
for i in l1:
    a = str(i)
    print(a)
    b.append(a)
    output = "".join(b)
print('b = ',b)  

11
22
33
b =  ['11', '22', '33']


In [30]:
l1 = [11,22,33]
b =[]
for i in l1:
    a = str(i)
    b.append(a)
output = ' '.join(b)
print(b)
print(output) 

['11', '22', '33']
11 22 33


In [31]:
l1 = [1, 2, 3, 4]
l1.pop()
l1

[1, 2, 3]

In [32]:
l1.pop(1)
l1

[1, 3]

In [33]:
l1 = [1, 2, 3, 4]
l1.remove(3)
l1

[1, 2, 4]

In [45]:
a = [1,2,3,4]
a[0]


1

In [46]:
a[0:2]

[1, 2]

In [48]:
l1 = [200,100,90,80,78]
l1.sort()
l1

[78, 80, 90, 100, 200]

In [50]:
l1 = [200,100,90,80,78]
l2 = sorted(l1)
l2

[78, 80, 90, 100, 200]

In [51]:
s = [78, 80, 90, 100, 200]
s.reverse()
s

[200, 100, 90, 80, 78]

In [56]:
list1 = [78,80,90,100,200]
list1[::-1]


[200, 100, 90, 80, 78]

In [58]:
list1 = [78,80,90,100,200]
list1.reverse()
list1

[200, 100, 90, 80, 78]

In [77]:
s = [1,2,3]
for i in reversed(s):
    print(i,end = " ")
  

3 2 1 

In [65]:
countries = ['India', 'USA', 'China']
# Printing Elements in Reversed Order
print("reversed list using reversed : ")
for c in reversed(countries):
    print(c,end=" ")

reversed list using reversed : 
China USA India 

In [21]:
n = 5
for i in range (1,n):
    print('val',i)
    for j in range (i,n-1):
        print('*',end ='  ')
    print()
    

val 1
*  *  *  
val 2
*  *  
val 3
*  
val 4



In [42]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
h=list(map(lambda x:x**2,l1))
j=list(map(lambda y:y**2,l2))
print('h =',h)
print('j =',j)

h = [1, 4, 9, 16]
j = [25, 36, 49, 64]


In [44]:
h=list(filter(lambda x:x%2==0,range(1,11)))
h

[2, 4, 6, 8, 10]

In [10]:
n= int(input('Enter the value of n = '))
sum = 0
for i in range(1,n+1):
    sum = sum + i
print('sum of first n number will be=',sum)

Enter the value of n = 10
sum of first n number will be= 55


In [12]:
l1 = [2, 4, 6, 8, 10]
l1.count(2)

1

In [13]:
len(l1)

5

In [14]:
max(l1)

10

In [15]:
min(l1)

2

In [3]:
import re

In [10]:
import re
text = """my name is vikas ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com"""
mobile_num = re.findall('[0-9]{10}',text)
mobile_num

['9595246251', '8805282800']

In [2]:
import re
text = """my name is vikas ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com
hr@gmail.com"""
mail_id = re.findall('[a-z,0-2]{2,20}[@][a-z.]{5,15}',text)
mail_id

['vikasugle12@gmail.com', 'hr@gmail.com']

In [3]:
import re
text = """my name is vikas ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com
hr@gmail.com     27/06/2021,27-06-2021"""
date = re.findall('[0-9]{2}/[0-9]{2}/[0-9]{4}',text)
date

['27/06/2021']

In [24]:
import re
text = """ 'vikasugle12@gmail.com','vikas.ugle@gmail.com','vikas_ugle@rediffmail.com','vikasugle@gmail.com' """
mail1 = re.findall('[a-z_.0-9]{5,40}[@][a-z.]{2,20}',text)
mail1

['vikasugle12@gmail.com',
 'vikas.ugle@gmail.com',
 'vikas_ugle@rediffmail.com',
 'vikasugle@gmail.com']

In [22]:
import re
text = """vikasugle12@gmail.com,vikas.ugle@gmail.com,vikas_ugle@rediffmail.com,vikasugle@gmail.com"""
mail2 = re.findall('[a-z_.0-2]{2,20}[@][a-z.]{5,15}',text)
mail2

['vikasugle12@gmail.com',
 'vikas.ugle@gmail.com',
 'vikas_ugle@rediffmail.com',
 'vikasugle@gmail.com']

In [25]:
import re
text = """my name is vikas ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com"""
mobile_num = re.findall('\d{10}',text)
mobile_num

['9595246251', '8805282800']

In [26]:
import re
text = """my name is vikas ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com
hr@gmail.com     27/06/2021,27-06-2021"""
date = re.findall('\d{2}[/]\d{2}[/]\d{4}',text)
date

['27/06/2021']

In [27]:
import re
text = """my name is vikas ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com
hr@gmail.com     27/06/2021,27-06-2021"""
date = re.findall('\d{2}[/-]\d{2}[/-]\d{4}',text)
date

['27/06/2021', '27-06-2021']

In [33]:
import re
text = """my name is Vikas Ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com
hr@gmail.com     27/06/2021,27-06-2021"""
name = re.findall('[a-z,A-Z]{4,5}',text)
name

['name',
 'Vikas',
 'Ugle,',
 'mobil',
 'numbe',
 'mail',
 'vikas',
 'ugle',
 'gmail',
 'gmail']

In [35]:
import re
text = """my name is Vikas Ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com
hr@gmail.com     27/06/2021,27-06-2021"""
name = re.findall('\d{2,6}',text)
name

['959524',
 '6251',
 '880528',
 '2800',
 '12',
 '27',
 '06',
 '2021',
 '27',
 '06',
 '2021']

In [43]:
import re
text = """my name is Vikas Ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com
hr@gmail.com     27/06/2021,27-06-2021"""
name = re.findall('[a-z,A-z]{4,5}[ ][a-z,A-z]{4,5}',text)
name

['Vikas Ugle,', 'obile numbe']

In [44]:
text = """my name is Vikas Ugle"""
space = re.findall('[ ]',text)
space

[' ', ' ', ' ', ' ']

In [46]:
text = """my name is Vikas Ugle"""
space = re.findall('\s',text)
space

[' ', ' ', ' ', ' ']

In [47]:
text = """my name is Vikas     Ugle"""
space = re.findall('\s{5}',text)
space

['     ']

In [56]:
text = """my name is Vikas     Ugale"""
space = re.findall('\S{4}',text)
space

['name', 'Vika', 'Ugal']

In [60]:
import re
text = """my name is Vikas Ugle,my mobile number is 9595246251,8805282800 and mail id is vikasugle12@gmail.com
hr@gmail.com     27/06/2021,27-06-2021"""
name = re.findall('\w{10}',text)
name

['9595246251', '8805282800', 'vikasugle1']

In [63]:
import re
text = """my name is Vikas Ugle 9595246251  @ *"""
words = re.findall('\W{1}',text)
words

[' ', ' ', ' ', ' ', ' ', ' ', ' ', '@', ' ', '*']

In [65]:
import re
text = """my name is Vikas Ugle 9595246251  @ *"""
words = re.findall('\w{5}',text)
words

['Vikas', '95952', '46251']

In [76]:
import re
text = """my name is Vikas Ugle Mobile 9595246251 """
number = re.findall(r'\b\d{10}\b',text)
number

['9595246251']

In [2]:
import numpy as np

In [7]:
array = np.array([[1,2,3,4,5],[5,2,6,7,8]])
array

array([[1, 2, 3, 4, 5],
       [5, 2, 6, 7, 8]])

In [8]:
type(array)

numpy.ndarray

In [9]:
array[0,0]

1

In [10]:
array[0,1]

2

In [12]:
arr1 = np.array([1,2,3,4,5.2],'float')
arr1

array([1. , 2. , 3. , 4. , 5.2])

In [13]:
arr1 = np.array([1,2,3,4,5.2],'int')
arr1

array([1, 2, 3, 4, 5])

In [14]:
arr1 = np.array([1,2,3,4,5.2],'complex')
arr1

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.2+0.j])

In [17]:
arr1 = np.array([1+2j,2,3,4,5.2],'int')
arr1

TypeError: can't convert complex to int

In [18]:
arr1 = np.array([1+2j,2,3,4,5.2],'float')
arr1

TypeError: can't convert complex to float

In [24]:
array = np.array([[1,2,3,4,5],[5,2,6,7,8]])
array

array([[1, 2, 3, 4, 5],
       [5, 2, 6, 7, 8]])

In [26]:
array = np.array([[1,2,3,4,5],[5,2,6,7,8]])
array.ndim

2

In [27]:
arr2 = np.array([[1,2,3,4,5],[9,4,5,8,7],[5,2,6,7,8]])
print(arr2)
print('Number of dimension are:     ',arr2.ndim)

[[1 2 3 4 5]
 [9 4 5 8 7]
 [5 2 6 7 8]]
Number of dimension are:      2


In [30]:
arr2 = np.array([[[1,2,3,4,5],[9,4,5,8,7],[5,2,6,7,8]]])
print(arr2)
print('Number of dimension are: ',arr2.ndim)

[[[1 2 3 4 5]
  [9 4 5 8 7]
  [5 2 6 7 8]]]
Number of dimension are:  3


In [34]:
array5 = np.array([1,2,3,4,5,'a'])
print(array5)

['1' '2' '3' '4' '5' 'a']


In [36]:
array5 = np.array([1,2,3,4,5.2])
print(array5)

[1.  2.  3.  4.  5.2]


In [35]:
array5 = np.array([1,2,3,4,5.2,'a'])
print(array5)

['1' '2' '3' '4' '5.2' 'a']


In [37]:
array5 = np.array([1,2,3,4,5.2,'a',5+2j])
print(array5)

['1' '2' '3' '4' '5.2' 'a' '(5+2j)']


In [38]:
arr2 = np.array([[1,2,3,4,5],[9,4,5,8,7],[5,2,6,7,8]])
print(arr2)
arr2[1,0]

[[1 2 3 4 5]
 [9 4 5 8 7]
 [5 2 6 7 8]]


9

In [39]:
arr2 = np.array([[1,2,3,4,5],[9,4,5,8,7],[5,2,6,7,8]])
print(arr2)
arr2[0,0]

[[1 2 3 4 5]
 [9 4 5 8 7]
 [5 2 6 7 8]]


1

In [45]:
arr2 = np.array([[[1,2,3,4,5],[9,4,5,8,7],[5,2,6,7,8]]])
print(arr2)
arr2[0,1,1]

[[[1 2 3 4 5]
  [9 4 5 8 7]
  [5 2 6 7 8]]]


4

In [54]:
arr2 = np.array([[1,2,3,4,5],[9,4,5,8,7],[5,2,6,7,8]])
print(arr2)
arr2[2]

[[1 2 3 4 5]
 [9 4 5 8 7]
 [5 2 6 7 8]]


array([5, 2, 6, 7, 8])

In [60]:
arr2[:2,:2]

array([[1, 2],
       [9, 4]])

In [64]:
arr2[1:3,3:5]

array([[8, 7],
       [7, 8]])

In [65]:
arr2[1:,3:]

array([[8, 7],
       [7, 8]])

In [66]:
arr2 = np.array([[1,2,3,4,5],[9,4,5,8,7],[5,2,6,7,8]])
print(arr2)

[[1 2 3 4 5]
 [9 4 5 8 7]
 [5 2 6 7 8]]


In [67]:
arr2[:2,2:4]

array([[3, 4],
       [5, 8]])

In [69]:
arr2.shape

(3, 5)

#shape >> no of rows ,no of column

In [70]:
arr2 = np.array([[1,2,3,4,5],[5,2,6,7,8]])
print(arr2)

[[1 2 3 4 5]
 [5 2 6 7 8]]


In [71]:
arr2.shape

(2, 5)

In [5]:
import numpy as np
arr1 = np.zeros([5,5])
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
import numpy as np
arr2 = np.zeros(250)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
import pandas as pd
df = pd.DataFrame(arr2)
df.to_csv('zeros.csv') 

In [29]:
import numpy as np
arr2 = np.zeros(350)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [39]:
import pandas as pd
df2 = pd.DataFrame(arr2)
df2.to_csv('zeros.csv') 
df2

0
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
..   ...
345  0.0
346  0.0
347  0.0
348  0.0
349  0.0

[350 rows x 1 columns]

In [35]:
import numpy as np
arr1 = np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [37]:
arr1 = np.ones([7,8],'int')
df1 = pd.DataFrame(arr1)
df1

0  1  2  3  4  5  6  7
0  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1
2  1  1  1  1  1  1  1  1
3  1  1  1  1  1  1  1  1
4  1  1  1  1  1  1  1  1
5  1  1  1  1  1  1  1  1
6  1  1  1  1  1  1  1  1

In [40]:
arr1 = np.ones([7,8],'int')
df1 = pd.DataFrame(arr1)
df1.to_csv('ones.csv') 

In [11]:
import numpy as np
arr1 = np.arange(1,5,1)
arr1

array([1, 2, 3, 4])

In [14]:
import numpy as np
arr1 = np.arange(1,10,3)
arr1

array([1, 4, 7])

In [18]:
arr1 = np.linspace(10,50,num=100)
arr1

array([10.        , 10.4040404 , 10.80808081, 11.21212121, 11.61616162,
       12.02020202, 12.42424242, 12.82828283, 13.23232323, 13.63636364,
       14.04040404, 14.44444444, 14.84848485, 15.25252525, 15.65656566,
       16.06060606, 16.46464646, 16.86868687, 17.27272727, 17.67676768,
       18.08080808, 18.48484848, 18.88888889, 19.29292929, 19.6969697 ,
       20.1010101 , 20.50505051, 20.90909091, 21.31313131, 21.71717172,
       22.12121212, 22.52525253, 22.92929293, 23.33333333, 23.73737374,
       24.14141414, 24.54545455, 24.94949495, 25.35353535, 25.75757576,
       26.16161616, 26.56565657, 26.96969697, 27.37373737, 27.77777778,
       28.18181818, 28.58585859, 28.98989899, 29.39393939, 29.7979798 ,
       30.2020202 , 30.60606061, 31.01010101, 31.41414141, 31.81818182,
       32.22222222, 32.62626263, 33.03030303, 33.43434343, 33.83838384,
       34.24242424, 34.64646465, 35.05050505, 35.45454545, 35.85858586,
       36.26262626, 36.66666667, 37.07070707, 37.47474747, 37.87

In [28]:
dict1 = {'zeros': np.zeros(10,'int'),
        'ones': np.ones(10,'int'),
        'arange': np.arange(11,21),
        'linspace': np.linspace(11,60)}
df = pd.DataFrame(dict1)
df

ValueError: arrays must all be same length

In [17]:
a = [10,20,30,10,20,30]
b = set(a)
b

{10, 20, 30}

In [22]:
c = list(b)
c

TypeError: 'list' object is not callable

In [25]:
set_sample = { 4, "hello" , 9 , 8.9 }
set_list = list (set_sample)
print (set_list)

TypeError: 'list' object is not callable

In [28]:
import itertools
a = [[1,2,3],[4,5,6]]
n1 = itertools.chain.from_iterable(a)
n1
print(list(n1))

TypeError: 'list' object is not callable